project_id = "xstqaapxufyrbstrzpvx"

[functions.youtube-metadata]
verify_jwt = false

[functions.analyze-transcript]
verify_jwt = false

[functions.render-video]
verify_jwt = false

[functions.check-render-status]
verify_jwt = false